<?xml version="1.0" encoding="UTF-8"?>
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>AddRelated</actionName>
        <type>Default</type>
    </actionOverrides>
    <actionOverrides>
        <actionName>CancelEdit</actionName>
        <type>Default</type>
    </actionOverrides>
    <actionOverrides>
        <actionName>Clone</actionName>
        <type>Default</type>
    </actionOverrides>
    <actionOverrides>
        <actionName>Create</actionName>
        <type>Default</type>
    </actionOverrides>
    <actionOverrides>
        <actionName>CreateRelated</actionName>
        <type>Default</type>
    </actionOverrides>
    <actionOverrides>
        <actionName>Delete</actionName>
        <type>Default</type>
    </actionOverrides>
    <actionOverrides>
        <actionName>Edit</actionName>
        <type>Default</type>
    </actionOverrides>
    <actionOverrides>
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides>
    <actionOverrides>
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides>
    <actionOverrides>
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides>
    <actionOverrides>
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides>
    <compactLayoutAssignment>SYSTEM</compactLayoutAssignment>
    <deploymentStatus>Deployed</deploymentStatus>
    <deprecated>false</deprecated>
    <description>Tracks d'apprentissage au sein d'un niveau</description>
    <enableActivities>true</enableActivities>
    <enableBulkApi>true</enableBulkApi>
    <enableFeeds>false</enableFeeds>
    <enableHistory>true</enableHistory>
    <enableLicensing>false</enableLicensing>
    <enableReports>true</enableReports>
    <enableSearch>true</enableSearch>
    <enableSharing>true</enableSharing>
    <enableStreamingApi>true</enableStreamingApi>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description du track</description>
        <externalId>false</externalId>
        <fieldManageability>DefinedByMetadata</fieldManageability>
        <label>Description</label>
        <length>32000</length>
        <required>false</required>
        <trackHistory>false</trackHistory>
        <trackTrending>false</trackTrending>
        <type>LongTextArea</type>
        <visibleLines>3</visibleLines>
    </fields>
    <fields>
        <fullName>Learning_Level__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Niveau parent (Foundation, Acquisition, Expansion)</description>
        <externalId>false</externalId>
        <fieldManageability>DefinedByMetadata</fieldManageability>
        <label>Learning Level</label>
        <referenceTo>Learning_Level__c</referenceTo>
        <relationshipLabel>Learning Tracks</relationshipLabel>
        <relationshipName>Learning_Tracks</relationshipName>
        <required>true</required>
        <trackHistory>false</trackHistory>
        <trackTrending>false</trackTrending>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>false</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>Ordre d'affichage du track au sein du niveau</description>
        <externalId>false</externalId>
        <fieldManageability>DefinedByMetadata</fieldManageability>
        <inlineHelpText>1, 2, 3, etc.</inlineHelpText>
        <label>Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <trackHistory>false</trackHistory>
        <trackTrending>false</trackTrending>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Required_Modules_Count__c</fullName>
        <description>Nombre de modules requis pour considérer le track comme complété</description>
        <externalId>false</externalId>
        <fieldManageability>DefinedByMetadata</fieldManageability>
        <label>Required Modules Count</label>
        <precision>3</precision>
        <required>false</required>
        <scale>0</scale>
        <trackHistory>false</trackHistory>
        <trackTrending>false</trackTrending>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Statut du track</description>
        <externalId>false</externalId>
        <fieldManageability>DefinedByMetadata</fieldManageability>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>false</default>
                <label>Draft</label>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
                <default>false</default>
                <label>Archived</label>
            </picklistValues>
            <sorted>false</sorted>
        </picklist>
        <required>true</required>
        <trackHistory>false</trackHistory>
        <trackTrending>false</trackTrending>
        <type>Picklist</type>
    </fields>
    <label>Learning Track</label>
    <listViews>
        <fullName>All</fullName>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews>
    <nameField>
        <label>Track Name</label>
        <trackHistory>false</trackHistory>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Tracks</pluralLabel>
    <recordTypeTrackHistory>false</recordTypeTrackHistory>
    <searchLayouts>
        <customTabListAdditionalFields>Learning_Level__c</customTabListAdditionalFields>
        <customTabListAdditionalFields>Order__c</customTabListAdditionalFields>
        <customTabListAdditionalFields>Status__c</customTabListAdditionalFields>
        <excludedStandardButtons>Accept</excludedStandardButtons>
        <excludedStandardButtons>ChangeOwnerOne</excludedStandardButtons>
        <excludedStandardButtons>Clone</excludedStandardButtons>
        <excludedStandardButtons>MassChangeOwner</excludedStandardButtons>
        <excludedStandardButtons>PrintableListView</excludedStandardButtons>
        <excludedStandardButtons>Share</excludedStandardButtons>
        <listViewButtons>New</listViewButtons>
        <lookupDialogsAdditionalFields>Learning_Level__c</lookupDialogsAdditionalFields>
        <lookupDialogsAdditionalFields>Order__c</lookupDialogsAdditionalFields>
        <lookupDialogsAdditionalFields>Status__c</lookupDialogsAdditionalFields>
        <searchResultsAdditionalFields>Learning_Level__c</searchResultsAdditionalFields>
        <searchResultsAdditionalFields>Order__c</searchResultsAdditionalFields>
        <searchResultsAdditionalFields>Status__c</searchResultsAdditionalFields>
    </searchLayouts>
    <sharingModel>ControlledByParent</sharingModel>
    <visibility>Public</visibility>
</CustomObject>
